/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sdxess;

import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kotaro
 */
public class details extends javax.swing.JFrame {

    public DefaultTableModel ipTableModel;
    public Website website;
    /**
     * Creates new form details
     */
    public details(Website website) {
        initComponents();
        URL iconURL = getClass().getResource("/sdxess/icon.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        this.website = website;
        
        this.setTitle(website.name + " detailed Info");
        
  
        this.ipTableModel = new javax.swing.table.DefaultTableModel(
            website.toRangesArray(),
            new String [] {
                "Network destination", "Netmask" , "Subnet"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        };
        ipTable.setModel(ipTableModel);
        
        this.nameValLabel.setText(website.name);
        this.ipValLabel.setText(website.IP);
        this.asnValLabel.setText(website.ASN);
        this.iprangesValLabel.setText(website.ranges.size()+"");
        this.descriptionValLabel.setText(website.Description);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ipTable = new javax.swing.JTable();
        nameLabel = new javax.swing.JLabel();
        ipLabel = new javax.swing.JLabel();
        asnLabel = new javax.swing.JLabel();
        iprangesLabel = new javax.swing.JLabel();
        nameValLabel = new javax.swing.JLabel();
        ipValLabel = new javax.swing.JLabel();
        asnValLabel = new javax.swing.JLabel();
        iprangesValLabel = new javax.swing.JLabel();
        descLabel = new javax.swing.JLabel();
        descriptionValLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ipTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ipTable);

        nameLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        nameLabel.setText("Domain Name:");

        ipLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ipLabel.setText("Tracked IP:");

        asnLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        asnLabel.setText("ASN: ");

        iprangesLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        iprangesLabel.setText("# of IP Ranges:");

        nameValLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nameValLabel.setText("google.com");

        ipValLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ipValLabel.setText("198.168.1.1");

        asnValLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        asnValLabel.setText("AS123456");

        iprangesValLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        iprangesValLabel.setText("250");

        descLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        descLabel.setText("Description:");

        descriptionValLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        descriptionValLabel.setText("Lorem ipsum dolor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(asnLabel)
                            .addComponent(iprangesLabel)
                            .addComponent(ipLabel)
                            .addComponent(nameLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameValLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ipValLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(iprangesValLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(asnValLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(descLabel)
                        .addGap(34, 34, 34)
                        .addComponent(descriptionValLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameValLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipLabel)
                    .addComponent(ipValLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asnLabel)
                    .addComponent(asnValLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iprangesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iprangesValLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionValLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asnLabel;
    private javax.swing.JLabel asnValLabel;
    private javax.swing.JLabel descLabel;
    private javax.swing.JLabel descriptionValLabel;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JTable ipTable;
    private javax.swing.JLabel ipValLabel;
    private javax.swing.JLabel iprangesLabel;
    private javax.swing.JLabel iprangesValLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameValLabel;
    // End of variables declaration//GEN-END:variables
}
